name: diet
# conda env create --file conda-env.yml
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.6
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - tensorflow-gpu=1.15
  - seaborn